sudo: false
language: python
cache: pip

stages:
  - name: test
  - name: deploy
    if: tag IS present

python:
  - "3.6"
  - "3.7"

install:
  - pip install tox-travis tox
script: tox

jobs:
  include:
    - stage: deploy
      python: 3.7
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: $PYPI_USER
        password: $PYPI_PASSWORD
        on:
          tags: true
        skip_existing: true
