sudo: false
language: python

python:
  - "3.6"
  - "3.7"

install: pip install tox-travis tox
script: tox
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
  skip_existing: true
